name: Build and Deploy Node.js app to Azure Web App - my-todo-app-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install client dependencies and build client
        run: |
          cd client
          npm install
          npm run build
          cd ..

      - name: Move client build to server/src
        run: |
          mkdir -p server/src
          cp -a client/dist/. server/src

      - name: Install server dependencies
        run: |
          cd server
          npm install
          cd ..

      - name: Zip server for deployment
        run: |
          cd server
          zip -r ../release.zip .
          cd ..

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-todo-app-pipeline'
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
