# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - my-todo-app-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install client dependencies and build client
        run: |
          cd client
          npm install
          npm run build
          cd ..

      - name: Move client build to server/src/dist
        run: |
          mkdir -p server/src/dist
          cp -a client/dist/. server/src/dist

      - name: Install server dependencies
        run: |
          cd server
          npm install
          cd ..

      - name: Zip server for deployment
        run: |
          cd server
          zip -r ../server.zip .
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip server.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D28BD7519D04519B6DBC205C5E43B50 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D672382431E4F8EB7DD84C286C8DAEF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_035985E611B24DB2A172B23DC02D7FF4 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-todo-app-pipeline'
          slot-name: 'Production'
          package: .
          
